"""Set default for quantities column to 'Unconfirmed as string'

Revision ID: 02129095cd72
Revises: 19423406e509
Create Date: 2025-01-09 05:57:51.145521

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '02129095cd72'
down_revision = '19423406e509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('quantities',
               existing_type=mysql.JSON(),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('quantities',
               existing_type=sa.String(length=255),
               type_=mysql.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###
