"""Add portal username and password to Order

Revision ID: 083fae28c1aa
Revises: 20c964cf7c4c
Create Date: 2025-01-05 04:10:39.495126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '083fae28c1aa'
down_revision = '20c964cf7c4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('portal_username', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('portal_password', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('portal_password')
        batch_op.drop_column('portal_username')

    # ### end Alembic commands ###
