"""Add new columns: first_name, last_name, organisation, etc.

Revision ID: 20c964cf7c4c
Revises: 278e9da9bc8f
Create Date: 2025-01-02 15:44:00.444704

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '20c964cf7c4c'
down_revision = '278e9da9bc8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('position', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('referral', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('delivery_instructions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('agree_to_promotions', sa.Boolean(), nullable=True))
        batch_op.alter_column('school_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('contact_person')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_person', mysql.VARCHAR(length=255), nullable=True))
        batch_op.alter_column('school_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('agree_to_promotions')
        batch_op.drop_column('delivery_instructions')
        batch_op.drop_column('referral')
        batch_op.drop_column('position')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
