"""Add kit_received_at to Order

Revision ID: 98e55724f607
Revises: 7eeb6ab80072
Create Date: 2025-01-07 19:59:58.865967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98e55724f607'
down_revision = '7eeb6ab80072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kit_received_at', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('kit_received_at')

    # ### end Alembic commands ###
