"""Add columns to Order without dropping tables

Revision ID: 278e9da9bc8f
Revises: e8e9a436cc06
Create Date: 2025-01-01 19:56:50.856308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '278e9da9bc8f'
down_revision = 'e8e9a436cc06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('product', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('free_sample', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('art_packs', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('address_line1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('address_line2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('county', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('postcode', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('postcode')
        batch_op.drop_column('county')
        batch_op.drop_column('city')
        batch_op.drop_column('address_line2')
        batch_op.drop_column('address_line1')
        batch_op.drop_column('art_packs')
        batch_op.drop_column('free_sample')
        batch_op.drop_column('product')
        batch_op.drop_column('reason')

    op.drop_table('user')
    op.drop_table('tasks')
    # ### end Alembic commands ###
